name:               topoi
version:            0.1.0.0
bug-reports:        https://github.com/topoi-lang/topoi/issues
license:            MIT
license-file:       LICENSE
author:             Topoi team
maintainer:         zypeh.geek@gmail.com
copyright:          Copyright (c) 2020, Topoi-lang
category:           Compiler, Language
extra-source-files: README.md

tested-with:        GHC == 8.8.2 # lts-15.3

dependencies:
- base >= 4.7 && < 5
- lexer-applicative
- megaparsec >= 8.0.0
- regex-applicative >= 0.3.3
- text >= 1.2.4
- unordered-containers >= 0.2.10

default-extensions:
- OverloadedStrings
- GeneralizedNewtypeDeriving

executables:
  topoi:
    source-dirs:
      src
      # compiler/src
      # terminal/src
    main:          Main.hs
    ghc-options:
      - -Wall
      - -Wextra
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N