name:               topoi
version:            0.1.0.0
bug-reports:        https://github.com/topoi-lang/topoi/issues
license:            MIT
license-file:       LICENSE
author:             Topoi team
maintainer:         zypeh.geek@gmail.com
copyright:          Copyright (c) 2020, Topoi-lang
category:           Compiler, Language
extra-source-files: README.md

tested-with:        GHC == 8.8.2 # lts-15.3

dependencies:
- base-noprelude >= 4.7 && < 5
- co-log         >= 0.4.0.0
- relude         >= 0.6.0.0

default-extensions:
- OverloadedStrings
- GeneralizedNewtypeDeriving

executables:
  topoi:
    source-dirs:
      compiler/src
      terminal/src
    main:          Main.hs
    other-modules:
      Prelude
      App.Monad
      App.Env
    ghc-options:
      - -Wall
      - -Wextra
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N