name:               topoi
version:            0.1.0.0
bug-reports:        https://github.com/topoi-lang/topoi/issues
license:            MIT
license-file:       LICENSE
author:             Topoi team
maintainer:         zypeh.geek@gmail.com
copyright:          Copyright (c) 2020, Topoi-lang
category:           Compiler, Language
extra-source-files: README.md

tested-with:        GHC == 8.8.2 # lts-15.3

dependencies:
- base >= 4.7 && < 5
- bytestring >= 0.10
- containers
- lexer-applicative
- megaparsec >= 8.0.0
- mtl
- parser-combinators
- regex-applicative >= 0.3.3
- srcloc >= 0.5
- text >= 1.2.4
- unordered-containers >= 0.2.10

executables:
  topoi:
    source-dirs:
      src
    main:          Terminal/Main.hs
    exposed_modules:
      Parse.Lexer
      Parse.TokenStream
      Parse.Topoi
      Parse.Utils

      Reporting.Annotation
      Reporting.Error

      Syntax.Abstract
      Syntax.Concrete

      Type.Error
    ghc-options:
      - -Wall
      - -Wextra
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -funbox-strict-fields
