name: topoi-tokenizer
version: 0.1.0.0
# synopsis
# description
maintainer: Zheng Yan PEH <zypeh.geek@gmail.com>
github: topoi-lang/topoi
category: Language
license-file: LICENSE

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

dependencies:
  - base
  - bytestring
  - template-haskell
  - word8

library:
  source-dirs: src
  exposed-modules:
    - Topoi.Compiler.Parser
    - Topoi.Compiler.Parser.Test